// MVP 节点集：与 GFM 对齐但 MVP 阶段 heading 只到 H4
export const nodes = {
  doc: { content: 'block+' },
  paragraph: {
    content: 'inline*',
    group: 'block',
    parseDOM: [{ tag: 'p' }],
    toDOM: () => ['p', 0] as const,
  },
  heading: {
    attrs: { level: { default: 1 } },
    content: 'inline*',
    group: 'block',
    defining: true,
    parseDOM: [1, 2, 3, 4].map((level) => ({ tag: `h${level}`, attrs: { level } })),
    toDOM: (node: any) => [`h${node.attrs.level}`, 0] as const,
  },
  blockquote: {
    content: 'block+',
    group: 'block',
    defining: true,
    parseDOM: [{ tag: 'blockquote' }],
    toDOM: () => ['blockquote', 0] as const,
  },
  codeBlock: {
    attrs: { language: { default: null } },
    content: 'text*',
    marks: '',
    group: 'block',
    code: true,
    defining: true,
    parseDOM: [{ tag: 'pre', preserveWhitespace: 'full' as const }],
    toDOM: () => ['pre', ['code', 0]] as const,
  },
  horizontalRule: {
    group: 'block',
    parseDOM: [{ tag: 'hr' }],
    toDOM: () => ['hr'] as const,
  },
  bulletList: {
    content: 'listItem+',
    group: 'block',
    parseDOM: [{ tag: 'ul' }],
    toDOM: () => ['ul', 0] as const,
  },
  orderedList: {
    attrs: { order: { default: 1 } },
    content: 'listItem+',
    group: 'block',
    parseDOM: [{ tag: 'ol' }],
    toDOM: () => ['ol', 0] as const,
  },
  listItem: {
    content: 'paragraph block*',
    defining: true,
    parseDOM: [{ tag: 'li' }],
    toDOM: () => ['li', 0] as const,
  },
  // GFM task list
  taskList: {
    content: 'taskItem+',
    group: 'block',
    parseDOM: [{ tag: 'ul[data-type="taskList"]' }],
    toDOM: () => ['ul', { 'data-type': 'taskList' }, 0] as const,
  },
  taskItem: {
    attrs: { checked: { default: false } },
    content: 'paragraph block*',
    defining: true,
    parseDOM: [{
      tag: 'li[data-type="taskItem"]',
      getAttrs: (el: HTMLElement) => ({ checked: el.getAttribute('data-checked') === 'true' }),
    }],
    toDOM: (node: any) => ['li', { 'data-type': 'taskItem', 'data-checked': String(!!node.attrs.checked) }, 0] as const,
  },
  // KaTeX math
  mathInline: {
    inline: true,
    atom: true,
    group: 'inline',
    attrs: { latex: { default: '' } },
    parseDOM: [{ tag: 'span.math-inline', getAttrs: (el: HTMLElement) => ({ latex: el.getAttribute('data-latex') ?? '' }) }],
    toDOM: (node: any) => ['span', { class: 'math-inline', 'data-latex': node.attrs.latex }, 0] as const,
  },
  mathDisplay: {
    atom: true,
    group: 'block',
    attrs: { latex: { default: '' } },
    parseDOM: [{ tag: 'div.math-display', getAttrs: (el: HTMLElement) => ({ latex: el.getAttribute('data-latex') ?? '' }) }],
    toDOM: (node: any) => ['div', { class: 'math-display', 'data-latex': node.attrs.latex }, 0] as const,
  },
  image: {
    inline: false,
    attrs: { src: {}, alt: { default: null } },
    group: 'block',
    draggable: true,
    parseDOM: [{ tag: 'img[src]' }],
    toDOM: (node: any) => ['img', { src: node.attrs.src, alt: node.attrs.alt }] as const,
  },
  table: {
    content: 'tableRow+',
    group: 'block',
    tableRole: 'table',
    isolating: true,
    parseDOM: [{ tag: 'table' }],
    toDOM: () => ['table', ['tbody', 0]] as const,
  },
  tableRow: {
    content: '(tableCell|tableHeader)+',
    tableRole: 'row',
    parseDOM: [{ tag: 'tr' }],
    toDOM: () => ['tr', 0] as const,
  },
  tableHeader: {
    content: 'paragraph+',
    tableRole: 'header_cell',
    isolating: true,
    parseDOM: [{ tag: 'th' }],
    toDOM: () => ['th', 0] as const,
  },
  tableCell: {
    content: 'paragraph+',
    tableRole: 'cell',
    isolating: true,
    parseDOM: [{ tag: 'td' }],
    toDOM: () => ['td', 0] as const,
  },
  text: { group: 'inline' },
  hardBreak: {
    inline: true,
    group: 'inline',
    selectable: false,
    parseDOM: [{ tag: 'br' }],
    toDOM: () => ['br'] as const,
  },
};
